import assert from "node:assert/strict";
import fs from "node:fs/promises";
import vm from "node:vm";
const source = await fs.readFile("plugins/web-apps/web/plugin.js", "utf8");
const plugin = await import(`data:text/javascript;base64,${Buffer.from(source).toString("base64")}`);
assert.equal(plugin.publicPrefix("/", "/app"), "/app/");
assert.equal(plugin.publicPrefix("/p/", "/app"), "/p/app/");
assert.equal(plugin.publicPrefix("/tenant/pilot", "/app"), "/tenant/pilot/app/");
let opened;
plugin.launchGateway({ ticket: "ticket", session: { id: "stream", publicationId: "generation", publicPrefix: "/p/app" } }, (...args) => { opened = args; });
assert.equal(opened[1], "_blank"); assert.equal(opened[2], "noopener,noreferrer");
assert.equal(new URL(opened[0], "https://host").search, ""); assert.equal(new URLSearchParams(new URL(opened[0], "https://host").hash.slice(1)).get("ticket"), "ticket");
for (const method of ["apps.targets.save", "apps.targets.delete", "apps.targets.list", "apps.session.open"]) assert.ok(source.includes(method));
const bootstrap = await fs.readFile("plugins/web-apps/web/bootstrap.js", "utf8");
let registration, removed = false, initialized, navigated = false;
const status = {};
const controller = { scriptURL: "https://host/multi/p/app/__runpilot__/sw.js?publication=generation", postMessage(message, ports) { assert.equal(removed, true); initialized = message; ports[0].peer.onmessage({ data: { ok: true } }); } };
class Channel { constructor() { this.port1 = { close() {} }; this.port2 = { peer: this.port1, close() {} }; } }
const context = { RUNPILOT_PUBLICATION: { publicPrefix: "/multi/p/app", publicationId: "generation" }, document: { getElementById() { return status; } }, location: { hash: "#ticket=one-use&stream=session&publication=generation", origin: "https://host", pathname: "/multi/p/app/", search: "", replace() { navigated = true; } }, history: { replaceState() { removed = true; } }, isSecureContext: true, crypto: { subtle: {} }, navigator: { serviceWorker: { register: async (url, options) => { registration = { url, options }; }, ready: Promise.resolve(), controller } }, localStorage: { credential: "legacy", removeItem() { this.credential = null; } }, URL, URLSearchParams, MessageChannel: Channel, setTimeout, clearTimeout };
vm.runInNewContext(await fs.readFile("internal/web/static/auth-storage.js", "utf8"), context);
await vm.runInNewContext(bootstrap, context);
assert.equal(context.localStorage.credential, null);
assert.equal(registration.options.scope, "/multi/p/app/"); assert.ok(new URL(registration.url).pathname === "/multi/p/app/__runpilot__/sw.js");
assert.equal(initialized.ticket, "one-use"); assert.equal(navigated, true);
context.isSecureContext = false; status.setAttribute = () => {};
await vm.runInNewContext(bootstrap, context); assert.match(status.textContent, /HTTPS/);
const worker = await fs.readFile("plugins/web-apps/web/sw.js", "utf8");
assert.ok(worker.includes("event.resultingClientId")); assert.ok(worker.includes("status: 503"));
assert.ok(!worker.includes("localStorage")); assert.ok(!worker.includes("sessionStorage"));
